Repository alan-turing-institute/grace, pull requests merged in 2023-09, with the labels that each got.

#199 Tensorboard launch command instructions
  grace/training/README.md
Labels: documentation

#131 Added show_starfile.py
  examples/show_starfile.py
Labels: enhancement, methodology

#196 Added instructions to export conda environment
  README.md
Labels: documentation

#200 Optional relabelling of nodes & edges with `Annotation.UNKNOWN` label
  grace/evaluation/visualisation.py
  grace/io/image_dataset.py
  grace/models/classifier.py
  grace/training/run.py
  grace/training/train.py
  notebooks/measure_metrics.ipynb
Labels: enhancement, methodology

#207 Implement new hyperparameters for training run config
  grace/models/feature_extractor.py
  grace/training/README.md
  grace/training/config.json
  grace/training/config.py
  grace/training/run.py
Labels: documentation, enhancement

#210 [WIP] 🚧 TheTuringWay PR template 👷‍♀️
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/method_development.md
  .github/ISSUE_TEMPLATE/old_templates/bug_report.yaml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#149 Visualisation of the image & graph annotations
  grace/napari/utils.py
  grace/utils/metrics.py
Labels: bug, documentation, enhancement

#178 added run test
  grace/io/image_dataset.py
  notebooks/run.ipynb
  setup.cfg
  tests/_utils.py
  tests/conftest.py
  tests/test_run.py
Labels: tests

#218 Training of GC Network -> debugging
  grace/models/classifier.py
  grace/models/datasets.py
  grace/training/train.py
  grace/utils/metrics.py
Labels: bug, documentation

#219 PR template update
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#223 Inference of GCN model on unseen test data
  grace/evaluation/__init__.py
  grace/evaluation/inference.py
  grace/evaluation/metrics_classifier.py
  grace/evaluation/metrics_objects.py
  grace/evaluation/utils.py
  grace/io/image_dataset.py
  grace/models/datasets.py
  grace/models/feature_extractor.py
  grace/training/README.md
  grace/training/config.json
  grace/training/config.py
  grace/training/run.py
  grace/training/train.py
  grace/utils/metrics.py
  notebooks/infer_predictions.ipynb
  notebooks/measure_metrics.ipynb
  notebooks/read_grace.ipynb
  tests/test_train.py
Labels: enhancement, methodology

#231 Modifying the optimiser input to more elaborate `PREDICTION` vector dtype
  grace/base.py
  grace/evaluation/manifold.py
  grace/evaluation/process.py
  grace/models/optimiser.py
  notebooks/infer_predictions.ipynb
  notebooks/measure_metrics.ipynb
  notebooks/read_grace.ipynb
  tests/test_dummy.py
  tests/test_optimiser.py
Labels: tests, methodology

#234 Subgraph visualisation 🌐 + plotting code re-organisation 📁
  grace/evaluation/inference.py
  grace/evaluation/metrics_classifier.py
  grace/evaluation/metrics_objects.py
  grace/training/README.md
  grace/training/config.py
  grace/training/config.yaml
  grace/visualisation/__init__.py
  grace/visualisation/annotate.py
  grace/visualisation/manifold.py
  grace/visualisation/plotting.py
  grace/visualisation/subgraph.py
  grace/visualisation/utils.py
  notebooks/infer_predictions.ipynb
  notebooks/measure_metrics.ipynb
  notebooks/read_grace.ipynb
Labels: enhancement, methodology

#250 Inference & optimisation (+ visualisation) all in automated pipeline 🚀
  README.md
  grace/evaluation/inference.py
  grace/evaluation/metrics_classifier.py
  grace/evaluation/metrics_objects.py
  grace/io/image_dataset.py
  grace/logger.py
  grace/models/classifier.py
  grace/models/optimiser.py
  grace/run.py
  grace/styling.py
  grace/training/README.md
  grace/training/config.json
  grace/training/config.py
  grace/training/config.yaml
  grace/training/run.py
  grace/training/train.py
  grace/visualisation/animation.py
  grace/visualisation/annotate.py
  grace/visualisation/annotation.py
  grace/visualisation/manifold.py
  grace/visualisation/plotting.py
  grace/visualisation/utils.py
  notebooks/infer_predictions.ipynb
  notebooks/measure_metrics.ipynb
  setup.cfg
  tests/test_run.py
  tests/test_train.py
Labels: documentation, enhancement, methodology

#273 Config hyperparameters for enhanced training
  grace/run.py
  grace/training/config.py
  grace/training/config.yaml
  grace/training/train.py
Labels: documentation, enhancement
